/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-20 at 23:06:08 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.eventcommentendpoint;

/**
 * Service definition for Eventcommentendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EventcommentendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Eventcommentendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the eventcommentendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://zeppa-cloud-1821.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "eventcommentendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Eventcommentendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Eventcommentendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getEventComment".
   *
   * This request holds the parameters needed by the eventcommentendpoint server.  After setting any
   * optional parameters, call the {@link GetEventComment#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetEventComment getEventComment(java.lang.Long id) throws java.io.IOException {
    GetEventComment result = new GetEventComment(id);
    initialize(result);
    return result;
  }

  public class GetEventComment extends EventcommentendpointRequest<com.minook.zeppa.eventcommentendpoint.model.EventComment> {

    private static final String REST_PATH = "eventcomment/{id}";

    /**
     * Create a request for the method "getEventComment".
     *
     * This request holds the parameters needed by the the eventcommentendpoint server.  After setting
     * any optional parameters, call the {@link GetEventComment#execute()} method to invoke the remote
     * operation. <p> {@link GetEventComment#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetEventComment(java.lang.Long id) {
      super(Eventcommentendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.eventcommentendpoint.model.EventComment.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEventComment setAlt(java.lang.String alt) {
      return (GetEventComment) super.setAlt(alt);
    }

    @Override
    public GetEventComment setFields(java.lang.String fields) {
      return (GetEventComment) super.setFields(fields);
    }

    @Override
    public GetEventComment setKey(java.lang.String key) {
      return (GetEventComment) super.setKey(key);
    }

    @Override
    public GetEventComment setOauthToken(java.lang.String oauthToken) {
      return (GetEventComment) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEventComment setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEventComment) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEventComment setQuotaUser(java.lang.String quotaUser) {
      return (GetEventComment) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEventComment setUserIp(java.lang.String userIp) {
      return (GetEventComment) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetEventComment setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetEventComment set(String parameterName, Object value) {
      return (GetEventComment) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertEventComment".
   *
   * This request holds the parameters needed by the eventcommentendpoint server.  After setting any
   * optional parameters, call the {@link InsertEventComment#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.minook.zeppa.eventcommentendpoint.model.EventComment}
   * @return the request
   */
  public InsertEventComment insertEventComment(com.minook.zeppa.eventcommentendpoint.model.EventComment content) throws java.io.IOException {
    InsertEventComment result = new InsertEventComment(content);
    initialize(result);
    return result;
  }

  public class InsertEventComment extends EventcommentendpointRequest<com.minook.zeppa.eventcommentendpoint.model.EventComment> {

    private static final String REST_PATH = "eventcomment";

    /**
     * Create a request for the method "insertEventComment".
     *
     * This request holds the parameters needed by the the eventcommentendpoint server.  After setting
     * any optional parameters, call the {@link InsertEventComment#execute()} method to invoke the
     * remote operation. <p> {@link InsertEventComment#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.eventcommentendpoint.model.EventComment}
     * @since 1.13
     */
    protected InsertEventComment(com.minook.zeppa.eventcommentendpoint.model.EventComment content) {
      super(Eventcommentendpoint.this, "POST", REST_PATH, content, com.minook.zeppa.eventcommentendpoint.model.EventComment.class);
    }

    @Override
    public InsertEventComment setAlt(java.lang.String alt) {
      return (InsertEventComment) super.setAlt(alt);
    }

    @Override
    public InsertEventComment setFields(java.lang.String fields) {
      return (InsertEventComment) super.setFields(fields);
    }

    @Override
    public InsertEventComment setKey(java.lang.String key) {
      return (InsertEventComment) super.setKey(key);
    }

    @Override
    public InsertEventComment setOauthToken(java.lang.String oauthToken) {
      return (InsertEventComment) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertEventComment setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertEventComment) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertEventComment setQuotaUser(java.lang.String quotaUser) {
      return (InsertEventComment) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertEventComment setUserIp(java.lang.String userIp) {
      return (InsertEventComment) super.setUserIp(userIp);
    }

    @Override
    public InsertEventComment set(String parameterName, Object value) {
      return (InsertEventComment) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listEventComment".
   *
   * This request holds the parameters needed by the eventcommentendpoint server.  After setting any
   * optional parameters, call the {@link ListEventComment#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListEventComment listEventComment() throws java.io.IOException {
    ListEventComment result = new ListEventComment();
    initialize(result);
    return result;
  }

  public class ListEventComment extends EventcommentendpointRequest<com.minook.zeppa.eventcommentendpoint.model.CollectionResponseEventComment> {

    private static final String REST_PATH = "eventcomment";

    /**
     * Create a request for the method "listEventComment".
     *
     * This request holds the parameters needed by the the eventcommentendpoint server.  After setting
     * any optional parameters, call the {@link ListEventComment#execute()} method to invoke the
     * remote operation. <p> {@link ListEventComment#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListEventComment() {
      super(Eventcommentendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.eventcommentendpoint.model.CollectionResponseEventComment.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListEventComment setAlt(java.lang.String alt) {
      return (ListEventComment) super.setAlt(alt);
    }

    @Override
    public ListEventComment setFields(java.lang.String fields) {
      return (ListEventComment) super.setFields(fields);
    }

    @Override
    public ListEventComment setKey(java.lang.String key) {
      return (ListEventComment) super.setKey(key);
    }

    @Override
    public ListEventComment setOauthToken(java.lang.String oauthToken) {
      return (ListEventComment) super.setOauthToken(oauthToken);
    }

    @Override
    public ListEventComment setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListEventComment) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListEventComment setQuotaUser(java.lang.String quotaUser) {
      return (ListEventComment) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListEventComment setUserIp(java.lang.String userIp) {
      return (ListEventComment) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListEventComment setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String filter;

    /**

     */
    public java.lang.String getFilter() {
      return filter;
    }

    public ListEventComment setFilter(java.lang.String filter) {
      this.filter = filter;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListEventComment setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String ordering;

    /**

     */
    public java.lang.String getOrdering() {
      return ordering;
    }

    public ListEventComment setOrdering(java.lang.String ordering) {
      this.ordering = ordering;
      return this;
    }

    @Override
    public ListEventComment set(String parameterName, Object value) {
      return (ListEventComment) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeEventComment".
   *
   * This request holds the parameters needed by the eventcommentendpoint server.  After setting any
   * optional parameters, call the {@link RemoveEventComment#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveEventComment removeEventComment(java.lang.Long id) throws java.io.IOException {
    RemoveEventComment result = new RemoveEventComment(id);
    initialize(result);
    return result;
  }

  public class RemoveEventComment extends EventcommentendpointRequest<Void> {

    private static final String REST_PATH = "eventcomment/{id}";

    /**
     * Create a request for the method "removeEventComment".
     *
     * This request holds the parameters needed by the the eventcommentendpoint server.  After setting
     * any optional parameters, call the {@link RemoveEventComment#execute()} method to invoke the
     * remote operation. <p> {@link RemoveEventComment#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveEventComment(java.lang.Long id) {
      super(Eventcommentendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveEventComment setAlt(java.lang.String alt) {
      return (RemoveEventComment) super.setAlt(alt);
    }

    @Override
    public RemoveEventComment setFields(java.lang.String fields) {
      return (RemoveEventComment) super.setFields(fields);
    }

    @Override
    public RemoveEventComment setKey(java.lang.String key) {
      return (RemoveEventComment) super.setKey(key);
    }

    @Override
    public RemoveEventComment setOauthToken(java.lang.String oauthToken) {
      return (RemoveEventComment) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveEventComment setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveEventComment) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveEventComment setQuotaUser(java.lang.String quotaUser) {
      return (RemoveEventComment) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveEventComment setUserIp(java.lang.String userIp) {
      return (RemoveEventComment) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveEventComment setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveEventComment set(String parameterName, Object value) {
      return (RemoveEventComment) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Eventcommentendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Eventcommentendpoint}. */
    @Override
    public Eventcommentendpoint build() {
      return new Eventcommentendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EventcommentendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEventcommentendpointRequestInitializer(
        EventcommentendpointRequestInitializer eventcommentendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(eventcommentendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
