/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-14 at 06:16:50 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.eventtagendpoint.model;

/**
 * Model definition for EventTag.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the eventtagendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EventTag extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long dayCreated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long hostId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> initial;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tagText;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> usersFollowingIds;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDayCreated() {
    return dayCreated;
  }

  /**
   * @param dayCreated dayCreated or {@code null} for none
   */
  public EventTag setDayCreated(java.lang.Long dayCreated) {
    this.dayCreated = dayCreated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getHostId() {
    return hostId;
  }

  /**
   * @param hostId hostId or {@code null} for none
   */
  public EventTag setHostId(java.lang.Long hostId) {
    this.hostId = hostId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getInitial() {
    return initial;
  }

  /**
   * @param initial initial or {@code null} for none
   */
  public EventTag setInitial(java.util.List<java.lang.Long> initial) {
    this.initial = initial;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public EventTag setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTagText() {
    return tagText;
  }

  /**
   * @param tagText tagText or {@code null} for none
   */
  public EventTag setTagText(java.lang.String tagText) {
    this.tagText = tagText;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public EventTag setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getUsersFollowingIds() {
    return usersFollowingIds;
  }

  /**
   * @param usersFollowingIds usersFollowingIds or {@code null} for none
   */
  public EventTag setUsersFollowingIds(java.util.List<java.lang.Long> usersFollowingIds) {
    this.usersFollowingIds = usersFollowingIds;
    return this;
  }

  @Override
  public EventTag set(String fieldName, Object value) {
    return (EventTag) super.set(fieldName, value);
  }

  @Override
  public EventTag clone() {
    return (EventTag) super.clone();
  }

}
