/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-24 at 19:53:37 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.zeppaeventtouserrelationshipendpoint;

/**
 * Service definition for Zeppaeventtouserrelationshipendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ZeppaeventtouserrelationshipendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Zeppaeventtouserrelationshipendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the zeppaeventtouserrelationshipendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://zeppa-cloud-1821.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "zeppaeventtouserrelationshipendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Zeppaeventtouserrelationshipendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Zeppaeventtouserrelationshipendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getZeppaEventToUserRelationship".
   *
   * This request holds the parameters needed by the zeppaeventtouserrelationshipendpoint server.
   * After setting any optional parameters, call the {@link GetZeppaEventToUserRelationship#execute()}
   * method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetZeppaEventToUserRelationship getZeppaEventToUserRelationship(java.lang.Long id) throws java.io.IOException {
    GetZeppaEventToUserRelationship result = new GetZeppaEventToUserRelationship(id);
    initialize(result);
    return result;
  }

  public class GetZeppaEventToUserRelationship extends ZeppaeventtouserrelationshipendpointRequest<com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship> {

    private static final String REST_PATH = "zeppaeventtouserrelationship/{id}";

    /**
     * Create a request for the method "getZeppaEventToUserRelationship".
     *
     * This request holds the parameters needed by the the zeppaeventtouserrelationshipendpoint
     * server.  After setting any optional parameters, call the {@link
     * GetZeppaEventToUserRelationship#execute()} method to invoke the remote operation. <p> {@link Ge
     * tZeppaEventToUserRelationship#initialize(com.google.api.client.googleapis.services.AbstractGoog
     * leClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetZeppaEventToUserRelationship(java.lang.Long id) {
      super(Zeppaeventtouserrelationshipendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetZeppaEventToUserRelationship setAlt(java.lang.String alt) {
      return (GetZeppaEventToUserRelationship) super.setAlt(alt);
    }

    @Override
    public GetZeppaEventToUserRelationship setFields(java.lang.String fields) {
      return (GetZeppaEventToUserRelationship) super.setFields(fields);
    }

    @Override
    public GetZeppaEventToUserRelationship setKey(java.lang.String key) {
      return (GetZeppaEventToUserRelationship) super.setKey(key);
    }

    @Override
    public GetZeppaEventToUserRelationship setOauthToken(java.lang.String oauthToken) {
      return (GetZeppaEventToUserRelationship) super.setOauthToken(oauthToken);
    }

    @Override
    public GetZeppaEventToUserRelationship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetZeppaEventToUserRelationship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetZeppaEventToUserRelationship setQuotaUser(java.lang.String quotaUser) {
      return (GetZeppaEventToUserRelationship) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetZeppaEventToUserRelationship setUserIp(java.lang.String userIp) {
      return (GetZeppaEventToUserRelationship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetZeppaEventToUserRelationship setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetZeppaEventToUserRelationship set(String parameterName, Object value) {
      return (GetZeppaEventToUserRelationship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertZeppaEventToUserRelationship".
   *
   * This request holds the parameters needed by the zeppaeventtouserrelationshipendpoint server.
   * After setting any optional parameters, call the {@link
   * InsertZeppaEventToUserRelationship#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship}
   * @return the request
   */
  public InsertZeppaEventToUserRelationship insertZeppaEventToUserRelationship(com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship content) throws java.io.IOException {
    InsertZeppaEventToUserRelationship result = new InsertZeppaEventToUserRelationship(content);
    initialize(result);
    return result;
  }

  public class InsertZeppaEventToUserRelationship extends ZeppaeventtouserrelationshipendpointRequest<com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship> {

    private static final String REST_PATH = "zeppaeventtouserrelationship";

    /**
     * Create a request for the method "insertZeppaEventToUserRelationship".
     *
     * This request holds the parameters needed by the the zeppaeventtouserrelationshipendpoint
     * server.  After setting any optional parameters, call the {@link
     * InsertZeppaEventToUserRelationship#execute()} method to invoke the remote operation. <p> {@link
     * InsertZeppaEventToUserRelationship#initialize(com.google.api.client.googleapis.services.Abstrac
     * tGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship}
     * @since 1.13
     */
    protected InsertZeppaEventToUserRelationship(com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship content) {
      super(Zeppaeventtouserrelationshipendpoint.this, "POST", REST_PATH, content, com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship.class);
    }

    @Override
    public InsertZeppaEventToUserRelationship setAlt(java.lang.String alt) {
      return (InsertZeppaEventToUserRelationship) super.setAlt(alt);
    }

    @Override
    public InsertZeppaEventToUserRelationship setFields(java.lang.String fields) {
      return (InsertZeppaEventToUserRelationship) super.setFields(fields);
    }

    @Override
    public InsertZeppaEventToUserRelationship setKey(java.lang.String key) {
      return (InsertZeppaEventToUserRelationship) super.setKey(key);
    }

    @Override
    public InsertZeppaEventToUserRelationship setOauthToken(java.lang.String oauthToken) {
      return (InsertZeppaEventToUserRelationship) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertZeppaEventToUserRelationship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertZeppaEventToUserRelationship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertZeppaEventToUserRelationship setQuotaUser(java.lang.String quotaUser) {
      return (InsertZeppaEventToUserRelationship) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertZeppaEventToUserRelationship setUserIp(java.lang.String userIp) {
      return (InsertZeppaEventToUserRelationship) super.setUserIp(userIp);
    }

    @Override
    public InsertZeppaEventToUserRelationship set(String parameterName, Object value) {
      return (InsertZeppaEventToUserRelationship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listZeppaEventToUserRelationship".
   *
   * This request holds the parameters needed by the zeppaeventtouserrelationshipendpoint server.
   * After setting any optional parameters, call the {@link
   * ListZeppaEventToUserRelationship#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListZeppaEventToUserRelationship listZeppaEventToUserRelationship() throws java.io.IOException {
    ListZeppaEventToUserRelationship result = new ListZeppaEventToUserRelationship();
    initialize(result);
    return result;
  }

  public class ListZeppaEventToUserRelationship extends ZeppaeventtouserrelationshipendpointRequest<com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.CollectionResponseZeppaEventToUserRelationship> {

    private static final String REST_PATH = "zeppaeventtouserrelationship";

    /**
     * Create a request for the method "listZeppaEventToUserRelationship".
     *
     * This request holds the parameters needed by the the zeppaeventtouserrelationshipendpoint
     * server.  After setting any optional parameters, call the {@link
     * ListZeppaEventToUserRelationship#execute()} method to invoke the remote operation. <p> {@link L
     * istZeppaEventToUserRelationship#initialize(com.google.api.client.googleapis.services.AbstractGo
     * ogleClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @since 1.13
     */
    protected ListZeppaEventToUserRelationship() {
      super(Zeppaeventtouserrelationshipendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.CollectionResponseZeppaEventToUserRelationship.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListZeppaEventToUserRelationship setAlt(java.lang.String alt) {
      return (ListZeppaEventToUserRelationship) super.setAlt(alt);
    }

    @Override
    public ListZeppaEventToUserRelationship setFields(java.lang.String fields) {
      return (ListZeppaEventToUserRelationship) super.setFields(fields);
    }

    @Override
    public ListZeppaEventToUserRelationship setKey(java.lang.String key) {
      return (ListZeppaEventToUserRelationship) super.setKey(key);
    }

    @Override
    public ListZeppaEventToUserRelationship setOauthToken(java.lang.String oauthToken) {
      return (ListZeppaEventToUserRelationship) super.setOauthToken(oauthToken);
    }

    @Override
    public ListZeppaEventToUserRelationship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListZeppaEventToUserRelationship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListZeppaEventToUserRelationship setQuotaUser(java.lang.String quotaUser) {
      return (ListZeppaEventToUserRelationship) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListZeppaEventToUserRelationship setUserIp(java.lang.String userIp) {
      return (ListZeppaEventToUserRelationship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListZeppaEventToUserRelationship setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String filter;

    /**

     */
    public java.lang.String getFilter() {
      return filter;
    }

    public ListZeppaEventToUserRelationship setFilter(java.lang.String filter) {
      this.filter = filter;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListZeppaEventToUserRelationship setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String ordering;

    /**

     */
    public java.lang.String getOrdering() {
      return ordering;
    }

    public ListZeppaEventToUserRelationship setOrdering(java.lang.String ordering) {
      this.ordering = ordering;
      return this;
    }

    @Override
    public ListZeppaEventToUserRelationship set(String parameterName, Object value) {
      return (ListZeppaEventToUserRelationship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeZeppaEventToUserRelationship".
   *
   * This request holds the parameters needed by the zeppaeventtouserrelationshipendpoint server.
   * After setting any optional parameters, call the {@link
   * RemoveZeppaEventToUserRelationship#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveZeppaEventToUserRelationship removeZeppaEventToUserRelationship(java.lang.Long id) throws java.io.IOException {
    RemoveZeppaEventToUserRelationship result = new RemoveZeppaEventToUserRelationship(id);
    initialize(result);
    return result;
  }

  public class RemoveZeppaEventToUserRelationship extends ZeppaeventtouserrelationshipendpointRequest<Void> {

    private static final String REST_PATH = "zeppaeventtouserrelationship/{id}";

    /**
     * Create a request for the method "removeZeppaEventToUserRelationship".
     *
     * This request holds the parameters needed by the the zeppaeventtouserrelationshipendpoint
     * server.  After setting any optional parameters, call the {@link
     * RemoveZeppaEventToUserRelationship#execute()} method to invoke the remote operation. <p> {@link
     * RemoveZeppaEventToUserRelationship#initialize(com.google.api.client.googleapis.services.Abstrac
     * tGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveZeppaEventToUserRelationship(java.lang.Long id) {
      super(Zeppaeventtouserrelationshipendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveZeppaEventToUserRelationship setAlt(java.lang.String alt) {
      return (RemoveZeppaEventToUserRelationship) super.setAlt(alt);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setFields(java.lang.String fields) {
      return (RemoveZeppaEventToUserRelationship) super.setFields(fields);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setKey(java.lang.String key) {
      return (RemoveZeppaEventToUserRelationship) super.setKey(key);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setOauthToken(java.lang.String oauthToken) {
      return (RemoveZeppaEventToUserRelationship) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveZeppaEventToUserRelationship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setQuotaUser(java.lang.String quotaUser) {
      return (RemoveZeppaEventToUserRelationship) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveZeppaEventToUserRelationship setUserIp(java.lang.String userIp) {
      return (RemoveZeppaEventToUserRelationship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveZeppaEventToUserRelationship setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveZeppaEventToUserRelationship set(String parameterName, Object value) {
      return (RemoveZeppaEventToUserRelationship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateZeppaEventToUserRelationship".
   *
   * This request holds the parameters needed by the zeppaeventtouserrelationshipendpoint server.
   * After setting any optional parameters, call the {@link
   * UpdateZeppaEventToUserRelationship#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship}
   * @return the request
   */
  public UpdateZeppaEventToUserRelationship updateZeppaEventToUserRelationship(com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship content) throws java.io.IOException {
    UpdateZeppaEventToUserRelationship result = new UpdateZeppaEventToUserRelationship(content);
    initialize(result);
    return result;
  }

  public class UpdateZeppaEventToUserRelationship extends ZeppaeventtouserrelationshipendpointRequest<com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship> {

    private static final String REST_PATH = "zeppaeventtouserrelationship";

    /**
     * Create a request for the method "updateZeppaEventToUserRelationship".
     *
     * This request holds the parameters needed by the the zeppaeventtouserrelationshipendpoint
     * server.  After setting any optional parameters, call the {@link
     * UpdateZeppaEventToUserRelationship#execute()} method to invoke the remote operation. <p> {@link
     * UpdateZeppaEventToUserRelationship#initialize(com.google.api.client.googleapis.services.Abstrac
     * tGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship}
     * @since 1.13
     */
    protected UpdateZeppaEventToUserRelationship(com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship content) {
      super(Zeppaeventtouserrelationshipendpoint.this, "PUT", REST_PATH, content, com.minook.zeppa.zeppaeventtouserrelationshipendpoint.model.ZeppaEventToUserRelationship.class);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setAlt(java.lang.String alt) {
      return (UpdateZeppaEventToUserRelationship) super.setAlt(alt);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setFields(java.lang.String fields) {
      return (UpdateZeppaEventToUserRelationship) super.setFields(fields);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setKey(java.lang.String key) {
      return (UpdateZeppaEventToUserRelationship) super.setKey(key);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setOauthToken(java.lang.String oauthToken) {
      return (UpdateZeppaEventToUserRelationship) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateZeppaEventToUserRelationship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setQuotaUser(java.lang.String quotaUser) {
      return (UpdateZeppaEventToUserRelationship) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateZeppaEventToUserRelationship setUserIp(java.lang.String userIp) {
      return (UpdateZeppaEventToUserRelationship) super.setUserIp(userIp);
    }

    @Override
    public UpdateZeppaEventToUserRelationship set(String parameterName, Object value) {
      return (UpdateZeppaEventToUserRelationship) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Zeppaeventtouserrelationshipendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Zeppaeventtouserrelationshipendpoint}. */
    @Override
    public Zeppaeventtouserrelationshipendpoint build() {
      return new Zeppaeventtouserrelationshipendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ZeppaeventtouserrelationshipendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setZeppaeventtouserrelationshipendpointRequestInitializer(
        ZeppaeventtouserrelationshipendpointRequestInitializer zeppaeventtouserrelationshipendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(zeppaeventtouserrelationshipendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
