/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-20 at 23:06:22 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.photoinfoendpoint;

/**
 * Service definition for Photoinfoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PhotoinfoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Photoinfoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the photoinfoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://zeppa-cloud-1821.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "photoinfoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Photoinfoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Photoinfoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPhotoInfo".
   *
   * This request holds the parameters needed by the photoinfoendpoint server.  After setting any
   * optional parameters, call the {@link GetPhotoInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPhotoInfo getPhotoInfo(java.lang.Long id) throws java.io.IOException {
    GetPhotoInfo result = new GetPhotoInfo(id);
    initialize(result);
    return result;
  }

  public class GetPhotoInfo extends PhotoinfoendpointRequest<com.minook.zeppa.photoinfoendpoint.model.PhotoInfo> {

    private static final String REST_PATH = "photoinfo/{id}";

    /**
     * Create a request for the method "getPhotoInfo".
     *
     * This request holds the parameters needed by the the photoinfoendpoint server.  After setting
     * any optional parameters, call the {@link GetPhotoInfo#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPhotoInfo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPhotoInfo(java.lang.Long id) {
      super(Photoinfoendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.photoinfoendpoint.model.PhotoInfo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPhotoInfo setAlt(java.lang.String alt) {
      return (GetPhotoInfo) super.setAlt(alt);
    }

    @Override
    public GetPhotoInfo setFields(java.lang.String fields) {
      return (GetPhotoInfo) super.setFields(fields);
    }

    @Override
    public GetPhotoInfo setKey(java.lang.String key) {
      return (GetPhotoInfo) super.setKey(key);
    }

    @Override
    public GetPhotoInfo setOauthToken(java.lang.String oauthToken) {
      return (GetPhotoInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPhotoInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPhotoInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPhotoInfo setQuotaUser(java.lang.String quotaUser) {
      return (GetPhotoInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPhotoInfo setUserIp(java.lang.String userIp) {
      return (GetPhotoInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPhotoInfo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPhotoInfo set(String parameterName, Object value) {
      return (GetPhotoInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPhotoInfo".
   *
   * This request holds the parameters needed by the photoinfoendpoint server.  After setting any
   * optional parameters, call the {@link InsertPhotoInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.minook.zeppa.photoinfoendpoint.model.PhotoInfo}
   * @return the request
   */
  public InsertPhotoInfo insertPhotoInfo(com.minook.zeppa.photoinfoendpoint.model.PhotoInfo content) throws java.io.IOException {
    InsertPhotoInfo result = new InsertPhotoInfo(content);
    initialize(result);
    return result;
  }

  public class InsertPhotoInfo extends PhotoinfoendpointRequest<com.minook.zeppa.photoinfoendpoint.model.PhotoInfo> {

    private static final String REST_PATH = "photoinfo";

    /**
     * Create a request for the method "insertPhotoInfo".
     *
     * This request holds the parameters needed by the the photoinfoendpoint server.  After setting
     * any optional parameters, call the {@link InsertPhotoInfo#execute()} method to invoke the remote
     * operation. <p> {@link InsertPhotoInfo#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.photoinfoendpoint.model.PhotoInfo}
     * @since 1.13
     */
    protected InsertPhotoInfo(com.minook.zeppa.photoinfoendpoint.model.PhotoInfo content) {
      super(Photoinfoendpoint.this, "POST", REST_PATH, content, com.minook.zeppa.photoinfoendpoint.model.PhotoInfo.class);
    }

    @Override
    public InsertPhotoInfo setAlt(java.lang.String alt) {
      return (InsertPhotoInfo) super.setAlt(alt);
    }

    @Override
    public InsertPhotoInfo setFields(java.lang.String fields) {
      return (InsertPhotoInfo) super.setFields(fields);
    }

    @Override
    public InsertPhotoInfo setKey(java.lang.String key) {
      return (InsertPhotoInfo) super.setKey(key);
    }

    @Override
    public InsertPhotoInfo setOauthToken(java.lang.String oauthToken) {
      return (InsertPhotoInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPhotoInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPhotoInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPhotoInfo setQuotaUser(java.lang.String quotaUser) {
      return (InsertPhotoInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPhotoInfo setUserIp(java.lang.String userIp) {
      return (InsertPhotoInfo) super.setUserIp(userIp);
    }

    @Override
    public InsertPhotoInfo set(String parameterName, Object value) {
      return (InsertPhotoInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPhotoInfo".
   *
   * This request holds the parameters needed by the photoinfoendpoint server.  After setting any
   * optional parameters, call the {@link ListPhotoInfo#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPhotoInfo listPhotoInfo() throws java.io.IOException {
    ListPhotoInfo result = new ListPhotoInfo();
    initialize(result);
    return result;
  }

  public class ListPhotoInfo extends PhotoinfoendpointRequest<com.minook.zeppa.photoinfoendpoint.model.CollectionResponsePhotoInfo> {

    private static final String REST_PATH = "photoinfo";

    /**
     * Create a request for the method "listPhotoInfo".
     *
     * This request holds the parameters needed by the the photoinfoendpoint server.  After setting
     * any optional parameters, call the {@link ListPhotoInfo#execute()} method to invoke the remote
     * operation. <p> {@link ListPhotoInfo#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPhotoInfo() {
      super(Photoinfoendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.photoinfoendpoint.model.CollectionResponsePhotoInfo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPhotoInfo setAlt(java.lang.String alt) {
      return (ListPhotoInfo) super.setAlt(alt);
    }

    @Override
    public ListPhotoInfo setFields(java.lang.String fields) {
      return (ListPhotoInfo) super.setFields(fields);
    }

    @Override
    public ListPhotoInfo setKey(java.lang.String key) {
      return (ListPhotoInfo) super.setKey(key);
    }

    @Override
    public ListPhotoInfo setOauthToken(java.lang.String oauthToken) {
      return (ListPhotoInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPhotoInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPhotoInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPhotoInfo setQuotaUser(java.lang.String quotaUser) {
      return (ListPhotoInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPhotoInfo setUserIp(java.lang.String userIp) {
      return (ListPhotoInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPhotoInfo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPhotoInfo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPhotoInfo set(String parameterName, Object value) {
      return (ListPhotoInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePhotoInfo".
   *
   * This request holds the parameters needed by the photoinfoendpoint server.  After setting any
   * optional parameters, call the {@link RemovePhotoInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePhotoInfo removePhotoInfo(java.lang.Long id) throws java.io.IOException {
    RemovePhotoInfo result = new RemovePhotoInfo(id);
    initialize(result);
    return result;
  }

  public class RemovePhotoInfo extends PhotoinfoendpointRequest<Void> {

    private static final String REST_PATH = "photoinfo/{id}";

    /**
     * Create a request for the method "removePhotoInfo".
     *
     * This request holds the parameters needed by the the photoinfoendpoint server.  After setting
     * any optional parameters, call the {@link RemovePhotoInfo#execute()} method to invoke the remote
     * operation. <p> {@link RemovePhotoInfo#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePhotoInfo(java.lang.Long id) {
      super(Photoinfoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePhotoInfo setAlt(java.lang.String alt) {
      return (RemovePhotoInfo) super.setAlt(alt);
    }

    @Override
    public RemovePhotoInfo setFields(java.lang.String fields) {
      return (RemovePhotoInfo) super.setFields(fields);
    }

    @Override
    public RemovePhotoInfo setKey(java.lang.String key) {
      return (RemovePhotoInfo) super.setKey(key);
    }

    @Override
    public RemovePhotoInfo setOauthToken(java.lang.String oauthToken) {
      return (RemovePhotoInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePhotoInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePhotoInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePhotoInfo setQuotaUser(java.lang.String quotaUser) {
      return (RemovePhotoInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePhotoInfo setUserIp(java.lang.String userIp) {
      return (RemovePhotoInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePhotoInfo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePhotoInfo set(String parameterName, Object value) {
      return (RemovePhotoInfo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Photoinfoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Photoinfoendpoint}. */
    @Override
    public Photoinfoendpoint build() {
      return new Photoinfoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PhotoinfoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPhotoinfoendpointRequestInitializer(
        PhotoinfoendpointRequestInitializer photoinfoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(photoinfoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
