/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-24 at 19:53:51 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.zeppauserendpoint.model;

/**
 * Model definition for ZeppaUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the zeppauserendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ZeppaUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String authEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long created;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String googleProfileId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long updated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ZeppaUserInfo userInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String zeppaCalendarId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthEmail() {
    return authEmail;
  }

  /**
   * @param authEmail authEmail or {@code null} for none
   */
  public ZeppaUser setAuthEmail(java.lang.String authEmail) {
    this.authEmail = authEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreated() {
    return created;
  }

  /**
   * @param created created or {@code null} for none
   */
  public ZeppaUser setCreated(java.lang.Long created) {
    this.created = created;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGoogleProfileId() {
    return googleProfileId;
  }

  /**
   * @param googleProfileId googleProfileId or {@code null} for none
   */
  public ZeppaUser setGoogleProfileId(java.lang.String googleProfileId) {
    this.googleProfileId = googleProfileId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ZeppaUser setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public ZeppaUser setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUpdated() {
    return updated;
  }

  /**
   * @param updated updated or {@code null} for none
   */
  public ZeppaUser setUpdated(java.lang.Long updated) {
    this.updated = updated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ZeppaUserInfo getUserInfo() {
    return userInfo;
  }

  /**
   * @param userInfo userInfo or {@code null} for none
   */
  public ZeppaUser setUserInfo(ZeppaUserInfo userInfo) {
    this.userInfo = userInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getZeppaCalendarId() {
    return zeppaCalendarId;
  }

  /**
   * @param zeppaCalendarId zeppaCalendarId or {@code null} for none
   */
  public ZeppaUser setZeppaCalendarId(java.lang.String zeppaCalendarId) {
    this.zeppaCalendarId = zeppaCalendarId;
    return this;
  }

  @Override
  public ZeppaUser set(String fieldName, Object value) {
    return (ZeppaUser) super.set(fieldName, value);
  }

  @Override
  public ZeppaUser clone() {
    return (ZeppaUser) super.clone();
  }

}
