/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-14 at 06:16:36 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.zeppauserendpoint.model;

/**
 * Model definition for ZeppaUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the zeppauserendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ZeppaUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> blockedUserIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> contactIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long dateJoined;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> deviceRegistrationIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> devices;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String familyName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> friendRequestIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String givenName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long lastEdited;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> newTagFollowerIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phoneNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getBlockedUserIds() {
    return blockedUserIds;
  }

  /**
   * @param blockedUserIds blockedUserIds or {@code null} for none
   */
  public ZeppaUser setBlockedUserIds(java.util.List<java.lang.Long> blockedUserIds) {
    this.blockedUserIds = blockedUserIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getContactIds() {
    return contactIds;
  }

  /**
   * @param contactIds contactIds or {@code null} for none
   */
  public ZeppaUser setContactIds(java.util.List<java.lang.Long> contactIds) {
    this.contactIds = contactIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDateJoined() {
    return dateJoined;
  }

  /**
   * @param dateJoined dateJoined or {@code null} for none
   */
  public ZeppaUser setDateJoined(java.lang.Long dateJoined) {
    this.dateJoined = dateJoined;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getDeviceRegistrationIds() {
    return deviceRegistrationIds;
  }

  /**
   * @param deviceRegistrationIds deviceRegistrationIds or {@code null} for none
   */
  public ZeppaUser setDeviceRegistrationIds(java.util.List<java.lang.String> deviceRegistrationIds) {
    this.deviceRegistrationIds = deviceRegistrationIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getDevices() {
    return devices;
  }

  /**
   * @param devices devices or {@code null} for none
   */
  public ZeppaUser setDevices(java.util.List<java.lang.String> devices) {
    this.devices = devices;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * @param displayName displayName or {@code null} for none
   */
  public ZeppaUser setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public ZeppaUser setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFamilyName() {
    return familyName;
  }

  /**
   * @param familyName familyName or {@code null} for none
   */
  public ZeppaUser setFamilyName(java.lang.String familyName) {
    this.familyName = familyName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getFriendRequestIds() {
    return friendRequestIds;
  }

  /**
   * @param friendRequestIds friendRequestIds or {@code null} for none
   */
  public ZeppaUser setFriendRequestIds(java.util.List<java.lang.Long> friendRequestIds) {
    this.friendRequestIds = friendRequestIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGivenName() {
    return givenName;
  }

  /**
   * @param givenName givenName or {@code null} for none
   */
  public ZeppaUser setGivenName(java.lang.String givenName) {
    this.givenName = givenName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }

  /**
   * @param imageUrl imageUrl or {@code null} for none
   */
  public ZeppaUser setImageUrl(java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public ZeppaUser setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLastEdited() {
    return lastEdited;
  }

  /**
   * @param lastEdited lastEdited or {@code null} for none
   */
  public ZeppaUser setLastEdited(java.lang.Long lastEdited) {
    this.lastEdited = lastEdited;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getNewTagFollowerIds() {
    return newTagFollowerIds;
  }

  /**
   * @param newTagFollowerIds newTagFollowerIds or {@code null} for none
   */
  public ZeppaUser setNewTagFollowerIds(java.util.List<java.lang.Long> newTagFollowerIds) {
    this.newTagFollowerIds = newTagFollowerIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  public ZeppaUser setPhoneNumber(java.lang.String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileId() {
    return profileId;
  }

  /**
   * @param profileId profileId or {@code null} for none
   */
  public ZeppaUser setProfileId(java.lang.String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public ZeppaUser setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public ZeppaUser set(String fieldName, Object value) {
    return (ZeppaUser) super.set(fieldName, value);
  }

  @Override
  public ZeppaUser clone() {
    return (ZeppaUser) super.clone();
  }

}
