/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-13 at 19:43:34 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.eventtagfollowendpoint.model;

/**
 * Model definition for EventTagFollow.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the eventtagfollowendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EventTagFollow extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long eventTagId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timeCreatedMillis;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userFollowingId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEventTagId() {
    return eventTagId;
  }

  /**
   * @param eventTagId eventTagId or {@code null} for none
   */
  public EventTagFollow setEventTagId(java.lang.Long eventTagId) {
    this.eventTagId = eventTagId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public EventTagFollow setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimeCreatedMillis() {
    return timeCreatedMillis;
  }

  /**
   * @param timeCreatedMillis timeCreatedMillis or {@code null} for none
   */
  public EventTagFollow setTimeCreatedMillis(java.lang.Long timeCreatedMillis) {
    this.timeCreatedMillis = timeCreatedMillis;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserFollowingId() {
    return userFollowingId;
  }

  /**
   * @param userFollowingId userFollowingId or {@code null} for none
   */
  public EventTagFollow setUserFollowingId(java.lang.Long userFollowingId) {
    this.userFollowingId = userFollowingId;
    return this;
  }

  @Override
  public EventTagFollow set(String fieldName, Object value) {
    return (EventTagFollow) super.set(fieldName, value);
  }

  @Override
  public EventTagFollow clone() {
    return (EventTagFollow) super.clone();
  }

}
