/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-20 at 15:31:23 UTC 
 * Modify at your own risk.
 */

package com.minook.zeppa.zeppauserendpoint;

/**
 * Service definition for Zeppauserendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ZeppauserendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Zeppauserendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the zeppauserendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://zeppa-cloud-1821.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "zeppauserendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Zeppauserendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Zeppauserendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "fetchMatchingUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link FetchMatchingUser#execute()} method to invoke the remote
   * operation.
   *
   * @param profileId
   * @return the request
   */
  public FetchMatchingUser fetchMatchingUser(java.lang.String profileId) throws java.io.IOException {
    FetchMatchingUser result = new FetchMatchingUser(profileId);
    initialize(result);
    return result;
  }

  public class FetchMatchingUser extends ZeppauserendpointRequest<com.minook.zeppa.zeppauserendpoint.model.ZeppaUser> {

    private static final String REST_PATH = "fetchMatchingUser/{profileId}";

    /**
     * Create a request for the method "fetchMatchingUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link FetchMatchingUser#execute()} method to invoke the
     * remote operation. <p> {@link FetchMatchingUser#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param profileId
     * @since 1.13
     */
    protected FetchMatchingUser(java.lang.String profileId) {
      super(Zeppauserendpoint.this, "POST", REST_PATH, null, com.minook.zeppa.zeppauserendpoint.model.ZeppaUser.class);
      this.profileId = com.google.api.client.util.Preconditions.checkNotNull(profileId, "Required parameter profileId must be specified.");
    }

    @Override
    public FetchMatchingUser setAlt(java.lang.String alt) {
      return (FetchMatchingUser) super.setAlt(alt);
    }

    @Override
    public FetchMatchingUser setFields(java.lang.String fields) {
      return (FetchMatchingUser) super.setFields(fields);
    }

    @Override
    public FetchMatchingUser setKey(java.lang.String key) {
      return (FetchMatchingUser) super.setKey(key);
    }

    @Override
    public FetchMatchingUser setOauthToken(java.lang.String oauthToken) {
      return (FetchMatchingUser) super.setOauthToken(oauthToken);
    }

    @Override
    public FetchMatchingUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FetchMatchingUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FetchMatchingUser setQuotaUser(java.lang.String quotaUser) {
      return (FetchMatchingUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public FetchMatchingUser setUserIp(java.lang.String userIp) {
      return (FetchMatchingUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String profileId;

    /**

     */
    public java.lang.String getProfileId() {
      return profileId;
    }

    public FetchMatchingUser setProfileId(java.lang.String profileId) {
      this.profileId = profileId;
      return this;
    }

    @Override
    public FetchMatchingUser set(String parameterName, Object value) {
      return (FetchMatchingUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getZeppaUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link GetZeppaUser#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @return the request
   */
  public GetZeppaUser getZeppaUser(java.lang.Long userId) throws java.io.IOException {
    GetZeppaUser result = new GetZeppaUser(userId);
    initialize(result);
    return result;
  }

  public class GetZeppaUser extends ZeppauserendpointRequest<com.minook.zeppa.zeppauserendpoint.model.ZeppaUser> {

    private static final String REST_PATH = "zeppauser/{userId}";

    /**
     * Create a request for the method "getZeppaUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link GetZeppaUser#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetZeppaUser#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param userId
     * @since 1.13
     */
    protected GetZeppaUser(java.lang.Long userId) {
      super(Zeppauserendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.zeppauserendpoint.model.ZeppaUser.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetZeppaUser setAlt(java.lang.String alt) {
      return (GetZeppaUser) super.setAlt(alt);
    }

    @Override
    public GetZeppaUser setFields(java.lang.String fields) {
      return (GetZeppaUser) super.setFields(fields);
    }

    @Override
    public GetZeppaUser setKey(java.lang.String key) {
      return (GetZeppaUser) super.setKey(key);
    }

    @Override
    public GetZeppaUser setOauthToken(java.lang.String oauthToken) {
      return (GetZeppaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public GetZeppaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetZeppaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetZeppaUser setQuotaUser(java.lang.String quotaUser) {
      return (GetZeppaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetZeppaUser setUserIp(java.lang.String userIp) {
      return (GetZeppaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public GetZeppaUser setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public GetZeppaUser set(String parameterName, Object value) {
      return (GetZeppaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertZeppaUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link InsertZeppaUser#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.minook.zeppa.zeppauserendpoint.model.ZeppaUser}
   * @return the request
   */
  public InsertZeppaUser insertZeppaUser(com.minook.zeppa.zeppauserendpoint.model.ZeppaUser content) throws java.io.IOException {
    InsertZeppaUser result = new InsertZeppaUser(content);
    initialize(result);
    return result;
  }

  public class InsertZeppaUser extends ZeppauserendpointRequest<com.minook.zeppa.zeppauserendpoint.model.ZeppaUser> {

    private static final String REST_PATH = "zeppauser";

    /**
     * Create a request for the method "insertZeppaUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link InsertZeppaUser#execute()} method to invoke the remote
     * operation. <p> {@link InsertZeppaUser#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.zeppauserendpoint.model.ZeppaUser}
     * @since 1.13
     */
    protected InsertZeppaUser(com.minook.zeppa.zeppauserendpoint.model.ZeppaUser content) {
      super(Zeppauserendpoint.this, "POST", REST_PATH, content, com.minook.zeppa.zeppauserendpoint.model.ZeppaUser.class);
    }

    @Override
    public InsertZeppaUser setAlt(java.lang.String alt) {
      return (InsertZeppaUser) super.setAlt(alt);
    }

    @Override
    public InsertZeppaUser setFields(java.lang.String fields) {
      return (InsertZeppaUser) super.setFields(fields);
    }

    @Override
    public InsertZeppaUser setKey(java.lang.String key) {
      return (InsertZeppaUser) super.setKey(key);
    }

    @Override
    public InsertZeppaUser setOauthToken(java.lang.String oauthToken) {
      return (InsertZeppaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertZeppaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertZeppaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertZeppaUser setQuotaUser(java.lang.String quotaUser) {
      return (InsertZeppaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertZeppaUser setUserIp(java.lang.String userIp) {
      return (InsertZeppaUser) super.setUserIp(userIp);
    }

    @Override
    public InsertZeppaUser set(String parameterName, Object value) {
      return (InsertZeppaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listZeppaUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link ListZeppaUser#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListZeppaUser listZeppaUser() throws java.io.IOException {
    ListZeppaUser result = new ListZeppaUser();
    initialize(result);
    return result;
  }

  public class ListZeppaUser extends ZeppauserendpointRequest<com.minook.zeppa.zeppauserendpoint.model.CollectionResponseZeppaUser> {

    private static final String REST_PATH = "zeppauser";

    /**
     * Create a request for the method "listZeppaUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link ListZeppaUser#execute()} method to invoke the remote
     * operation. <p> {@link ListZeppaUser#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListZeppaUser() {
      super(Zeppauserendpoint.this, "GET", REST_PATH, null, com.minook.zeppa.zeppauserendpoint.model.CollectionResponseZeppaUser.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListZeppaUser setAlt(java.lang.String alt) {
      return (ListZeppaUser) super.setAlt(alt);
    }

    @Override
    public ListZeppaUser setFields(java.lang.String fields) {
      return (ListZeppaUser) super.setFields(fields);
    }

    @Override
    public ListZeppaUser setKey(java.lang.String key) {
      return (ListZeppaUser) super.setKey(key);
    }

    @Override
    public ListZeppaUser setOauthToken(java.lang.String oauthToken) {
      return (ListZeppaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListZeppaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListZeppaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListZeppaUser setQuotaUser(java.lang.String quotaUser) {
      return (ListZeppaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListZeppaUser setUserIp(java.lang.String userIp) {
      return (ListZeppaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListZeppaUser setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListZeppaUser setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListZeppaUser set(String parameterName, Object value) {
      return (ListZeppaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeZeppaUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link RemoveZeppaUser#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveZeppaUser removeZeppaUser(java.lang.Long id) throws java.io.IOException {
    RemoveZeppaUser result = new RemoveZeppaUser(id);
    initialize(result);
    return result;
  }

  public class RemoveZeppaUser extends ZeppauserendpointRequest<Void> {

    private static final String REST_PATH = "zeppauser/{id}";

    /**
     * Create a request for the method "removeZeppaUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link RemoveZeppaUser#execute()} method to invoke the remote
     * operation. <p> {@link RemoveZeppaUser#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveZeppaUser(java.lang.Long id) {
      super(Zeppauserendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveZeppaUser setAlt(java.lang.String alt) {
      return (RemoveZeppaUser) super.setAlt(alt);
    }

    @Override
    public RemoveZeppaUser setFields(java.lang.String fields) {
      return (RemoveZeppaUser) super.setFields(fields);
    }

    @Override
    public RemoveZeppaUser setKey(java.lang.String key) {
      return (RemoveZeppaUser) super.setKey(key);
    }

    @Override
    public RemoveZeppaUser setOauthToken(java.lang.String oauthToken) {
      return (RemoveZeppaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveZeppaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveZeppaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveZeppaUser setQuotaUser(java.lang.String quotaUser) {
      return (RemoveZeppaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveZeppaUser setUserIp(java.lang.String userIp) {
      return (RemoveZeppaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveZeppaUser setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveZeppaUser set(String parameterName, Object value) {
      return (RemoveZeppaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateZeppaUser".
   *
   * This request holds the parameters needed by the zeppauserendpoint server.  After setting any
   * optional parameters, call the {@link UpdateZeppaUser#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.minook.zeppa.zeppauserendpoint.model.ZeppaUser}
   * @return the request
   */
  public UpdateZeppaUser updateZeppaUser(com.minook.zeppa.zeppauserendpoint.model.ZeppaUser content) throws java.io.IOException {
    UpdateZeppaUser result = new UpdateZeppaUser(content);
    initialize(result);
    return result;
  }

  public class UpdateZeppaUser extends ZeppauserendpointRequest<com.minook.zeppa.zeppauserendpoint.model.ZeppaUser> {

    private static final String REST_PATH = "zeppauser";

    /**
     * Create a request for the method "updateZeppaUser".
     *
     * This request holds the parameters needed by the the zeppauserendpoint server.  After setting
     * any optional parameters, call the {@link UpdateZeppaUser#execute()} method to invoke the remote
     * operation. <p> {@link UpdateZeppaUser#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.minook.zeppa.zeppauserendpoint.model.ZeppaUser}
     * @since 1.13
     */
    protected UpdateZeppaUser(com.minook.zeppa.zeppauserendpoint.model.ZeppaUser content) {
      super(Zeppauserendpoint.this, "PUT", REST_PATH, content, com.minook.zeppa.zeppauserendpoint.model.ZeppaUser.class);
    }

    @Override
    public UpdateZeppaUser setAlt(java.lang.String alt) {
      return (UpdateZeppaUser) super.setAlt(alt);
    }

    @Override
    public UpdateZeppaUser setFields(java.lang.String fields) {
      return (UpdateZeppaUser) super.setFields(fields);
    }

    @Override
    public UpdateZeppaUser setKey(java.lang.String key) {
      return (UpdateZeppaUser) super.setKey(key);
    }

    @Override
    public UpdateZeppaUser setOauthToken(java.lang.String oauthToken) {
      return (UpdateZeppaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateZeppaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateZeppaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateZeppaUser setQuotaUser(java.lang.String quotaUser) {
      return (UpdateZeppaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateZeppaUser setUserIp(java.lang.String userIp) {
      return (UpdateZeppaUser) super.setUserIp(userIp);
    }

    @Override
    public UpdateZeppaUser set(String parameterName, Object value) {
      return (UpdateZeppaUser) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Zeppauserendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Zeppauserendpoint}. */
    @Override
    public Zeppauserendpoint build() {
      return new Zeppauserendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ZeppauserendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setZeppauserendpointRequestInitializer(
        ZeppauserendpointRequestInitializer zeppauserendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(zeppauserendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
